version: ""

formatter: markdown table

name: terraform-fortios-ikev2-hub-spoke-vpn-generator

content: |-
  # terraform-fortios-ikev2-hub-spoke-vpn-generator

  GitHub: [StratusGrid/terraform-fortios-ikev2-hub-spoke-vpn-generator](https://github.com/StratusGrid/terraform-fortios-ikev2-hub-spoke-vpn-generator)

  This module takes a list of VPN configuration objects and makes a VPN for each side.

  Additionally, it outputs a map of the tunnel interface => IPs to dynamically add to OSPF, Firewall rules, etc.

  There is the need to make the module more dynamic and expandable by using variables where appropriate. May be worth having a vpn_mappings_advanced, then combining the maps in a local with default values or similar in the future, to allow things to be optionally defined without introducing breaking changes.

  ## Example Configuration:

  ```hcl
  {{ include "examples/example1.tfnot" }}
  ```
  ---

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  <span style="color:red">Note:</span> Manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml .`

sections:
  show:
    - resources
    - inputs
    - outputs
    - providers
    - requirements

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace
